server:
  servlet:
    context-path: /reactive

r2dbc:
#  hostname: host.docker.internal
  hostname: localhost
  database: test
  port: 3306
  username: root
  password: Thebreaker
  connection-timeout: 10
  pool:
    initial-size: 4
    max-size: 4
    max-idle-time: 90
    max-acquire-time: 5
    max-create-connection-time: 10
    max-life-time: 1800
