server:
  port: 8090
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    actuator:
      enabled: true
    prometheus:
      enabled: true
    jmx:
      exposure:
        include: '*'
    web:
      base-path: /
      path-mapping:
        prometheus: /prometheus
        health: /health
        info: /info
      exposure:
        include: info,prometheus,health

r2dbc:
  hostname: host.docker.internal
#  hostname: localhost
  database: test
  port: 3306
  username: root
  password: Thebreaker
  connection-timeout: 10
  pool:
    initial-size: 2
    max-size: 8
    max-idle-time: 90
    max-acquire-time: 5
    max-create-connection-time: 10
    max-life-time: 1800

boredapi:
  host: http://host.docker.internal:9100
  path:
    get-activity: /api/activity