server:
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: 30s

r2dbc:
  hostname: host.docker.internal
#  hostname: localhost
  database: test
  port: 3306
  username: root
  password: Thebreaker
  connection-timeout: 10
  pool:
    initial-size: 2
    max-size: 8
    max-idle-time: 90
    max-acquire-time: 5
    max-create-connection-time: 10
    max-life-time: 1800

boredapi:
  host: https://www.boredapi.com
  path:
    get-activity: /api/activity